apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: mongodb-connect-cluster4
  namespace: kafka
  annotations:
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  version: 2.8.0
  image: james4230/connect-mongodb:latest
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap.kafka.svc:9093
  tls:
    trustedCertificates:
      - secretName: kafka-cluster-cluster-ca-cert
        certificate: ca.crt
  config:
    #group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    #build:
    #output: 
    #type: docker
    #image: docker.io/james4230/connect-mongodb:latest 
      #pushSecret: my-registry-credentials
      #plugins: 
      #- name: debezium-mongodb-connector
      #artifacts:
      #- type: tgz
      #url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-mongodb/1.6.0.Final/debezium-connector-mongodb-1.6.0.Final-plugin.tar.gz
      
      #sha512sum: 962a12151bdf9a5a30627eebac739955a4fd95a08d373b86bdcea2b4d0c27dd6e1edd5cb548045e115e33a9e69b1b2a352bee24df035a0447cb820077af00c03
      #- name: camel-telegram
      #artifacts:
      #- type: tgz
      #url: https://repo.maven.apache.org/maven2/org/apache/camel/kafkaconnector/camel-telegram-kafka-connector/0.7.0/camel-telegram-kafka-connector-0.7.0-package.tar.gz
      #sha512sum: a9b1ac63e3284bea7836d7d24d84208c49cdf5600070e6bd1535de654f6920b74ad950d51733e8020bf4187870699819f54ef5859c7846ee4081507f48873479
