apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 2.8.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094 #Port number used by the listener inside Kafka
        type: nodeport
        tls: false  #Enables TLS encryption on the listener. Default is false. TLS encryption is not required for route listeners
        #authentication:
        # type: tls #Authentication specified as tls 
        #configuration:
        #  preferredNodePortAddressType: InternalDNS #(Optional, for nodeport listeners only) Configuration to specify a preference for the first address type used by Strimzi as the node address
        #authorization:
        #type: simple
        #superUsers:
        #- super-user-name

    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

